### ISSUE TITLE
That program is not running in my pc

### ISSUE THREAD

**Issue by MVinod791** [nuxy/slot-machine-gen#5]
I am getting lots of errors

**Comment by nuxy** [comment]
In order to further assist please provide the following information:
- Error messages, screenshot of `console` log or equivalent.
- Example of your implementation.

And finally, I suggesting running the [demo](https://github.com/nuxy/slot-machine-gen/tree/master/demo).
```
$ npm run build
```
If this works, then it's a configuration issue on your end.

**Comment by nuxy** [comment]
Closing this issue since it's [unrelated](https://github.com/MarsHeer/ReactJS-Slots-Machines/issues/1) to this library.
